apiVersion: apps.k8smgmt.io/v3
kind: Override
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: valuesFile
  name: k8syaml-co
  project: defaultproject
spec:
  placement: {}
  resource:
    type: Workload
  type: Yaml
