apiVersion: apps.k8smgmt.io/v3
kind: Override
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: valuesFile
  name: new-new
  project: defaultproject
spec:
  placement: {}
  resource:
    type: Addon
  type: Yaml
