apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gajanan-test
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAYG0I+Oiv++Rzymuy9hxrqI2S/haTTTT0qMWIbg8r5TeqSw4zaKb9lYhBpKDxQhZP5YInQdjp4r4gIsRnU1WRZevE08ILFDDzomBTv6WdpOpAGEfj5I/cfOipd5z8z/5GVYOjJSThiov51D6p5gqFqAfnnbNiGFrEMcU5DMS8UoUymcL7UMnzpE/hhFmNdf55OdswuHyp/lFXPnEynVfp5t5yrylKfvgyJZ4umPa4cYhnyBGwmx9crbpYBAffSh8XlpY6NgLAp3KowCLyl8VbgcXbmDbpUmsEVxyC5CtEz5t5PmwFsnnpWu4NkMV5oXSIvzhwd5TjfBLI6nv1T5qPadDfx+6kmdrDZ871eJ8WrExjdJLL9EFbMdKd3qlL/1VoYhIEQH1+Oc3nxOuPFsYvsyTccyFSfrAU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gajanan-test
      namespace: default

