apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUd4akNDQmE2Z0F3SUJBZ0lKQU9HU2NpdEFUL1JCTUEwR0NTcUdTSWIzRFFFQkN3VUFNSUcwTVFzd0NRWUQKVlFRR0V3SlZVekVRTUE0R0ExVUVDQk1IUVhKcGVtOXVZVEVUTUJFR0ExVUVCeE1LVTJOdmRIUnpaR0ZzWlRFYQpNQmdHQTFVRUNoTVJSMjlFWVdSa2VTNWpiMjBzSUVsdVl5NHhMVEFyQmdOVkJBc1RKR2gwZEhBNkx5OWpaWEowCmN5NW5iMlJoWkdSNUxtTnZiUzl5WlhCdmMybDBiM0o1THpFek1ERUdBMVVFQXhNcVIyOGdSR0ZrWkhrZ1UyVmoKZFhKbElFTmxjblJwWm1sallYUmxJRUYxZEdodmNtbDBlU0F0SUVjeU1CNFhEVEl3TURVeU1URXlNRGt5TUZvWApEVEl5TURjeU1ERTVOVFF4TkZvd1FqRWhNQjhHQTFVRUN4TVlSRzl0WVdsdUlFTnZiblJ5YjJ3Z1ZtRnNhV1JoCmRHVmtNUjB3R3dZRFZRUUREQlFxTG5KMWJpNXlZV1poZVMxbFpHZGxMbTVsZERDQ0FTSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU9oZlYzWFlNVmZES1N6S0lqNEdNTENvaVQ2QlBzZzJTVmpQdXJ6VAp5ekxvUXJnSkdRdGxVeXQ3UUZEQWp2M1FKeHJHZko0WFcxeUNlUlV5S0s3ZjJKTFR0S2FXQ3dZSnNRNVdHOHZmCk93bncvQndneXF1UDROVmp6Z1hqK0swUmVFS2d2UDlPUUliRWEvM25YWUJIOVRTSGd4d3YvcU1pSWEvVERKbjkKTU1sQWZJaXZrK000dXNTOG1odkhwT0k4V0VrNVJ6MDNvckJxL2NTYXJYVjY5NThaUDRPa1lGRWVubHFjK2trVgpLaGpWRG9ONHUvZWp1N09RS05uZlBRSFhTSUdIcStIL2dHZVJjTGgvWjJHQm9xVWhZY1lEeERNL3doK1p2am9tClNvTC95MXlEMnBGV0p3Z0ZDYWl6UjhTWUd3bmFnQmRBQkd6WDdBK3dJYy9sazdzQ0F3RUFBYU9DQTBvd2dnTkcKTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUE0RwpBMVVkRHdFQi93UUVBd0lGb0RBNEJnTlZIUjhFTVRBdk1DMmdLNkFwaGlkb2RIUndPaTh2WTNKc0xtZHZaR0ZrClpIa3VZMjl0TDJka2FXY3ljekV0TVRrNE1TNWpjbXd3WFFZRFZSMGdCRll3VkRCSUJndGdoa2dCaHYxdEFRY1gKQVRBNU1EY0dDQ3NHQVFVRkJ3SUJGaXRvZEhSd09pOHZZMlZ5ZEdsbWFXTmhkR1Z6TG1kdlpHRmtaSGt1WTI5dApMM0psY0c5emFYUnZjbmt2TUFnR0JtZUJEQUVDQVRCMkJnZ3JCZ0VGQlFjQkFRUnFNR2d3SkFZSUt3WUJCUVVICk1BR0dHR2gwZEhBNkx5OXZZM053TG1kdlpHRmtaSGt1WTI5dEx6QkFCZ2dyQmdFRkJRY3dBb1kwYUhSMGNEb3YKTDJObGNuUnBabWxqWVhSbGN5NW5iMlJoWkdSNUxtTnZiUzl5WlhCdmMybDBiM0o1TDJka2FXY3lMbU55ZERBZgpCZ05WSFNNRUdEQVdnQlJBd3IwbmpzdzBnekNpTTlmN2JMUHd0Q3lBempBekJnTlZIUkVFTERBcWdoUXFMbkoxCmJpNXlZV1poZVMxbFpHZGxMbTVsZElJU2NuVnVMbkpoWm1GNUxXVmtaMlV1Ym1WME1CMEdBMVVkRGdRV0JCUjUKZnhZb3ZvdkduTllHYlVreTlVYS95TDBzU3pDQ0FYOEdDaXNHQVFRQjFua0NCQUlFZ2dGdkJJSUJhd0ZwQUhZQQp1OW5mdkIrS2NiV1RsQ09YcXBKN1J6aFhsUXFyVXVnYWtKWmtObzRlMFlVQUFBRnlOeU5rbUFBQUJBTUFSekJGCkFpQmEvN3VNOEU4UnlMcG03YW9Sb0xBYS80T0d5M1RySjZ0TzNXSG03R3QzQndJaEFOS1krVEZJMWpWZ2M5MHkKUkNiZWJZWjdJaFBlVEZhWi9GaU9MMmhzQXhzSUFIY0FScVZWNjNYNmtTQXd0YUtKYWZUemZSRXNRWFMrL1VtNApoYXZ5L0hEK2JVY0FBQUZ5TnlOcExRQUFCQU1BU0RCR0FpRUErRFhPYWNudC8rMVlIRzdmZEVFU0JPQ2hzSjZlCndpZitnNERha0JUQXFhc0NJUUNiZVRQWkF1Mk5lOHJNUnI3ZThsWkxwcEpPdzJVQW5qZ1dzWnZYMzVMRVdRQjIKQUZZVUJwb3YxOExzMC9YaHZVU3lQc2RHZHJtOG1SRmN3TytVbUZYV2lkRGRBQUFCY2pjamFvMEFBQVFEQUVjdwpSUUloQVBaanR6Rm5jalZHcEVCTVpQZW9YL0I1OExqQ1BNQzdZSEg5c2ZZUEhaV1VBaUJWakZkbS9tZlBxWVlYCk9XNHVSZnFQUXo3a0JMMzMvZW92Z1Y4M0o0K3NBakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBSEgweUdzUGkKeXdSczBiTkVDSDkvUjRuaDhHT2tnOVpSV1lNUFFzUVZaVEhrdjd3UlNJSm40UThYa3M1ZHRoaTVSWGg1Y1lMQgpYUHNIUlQ0cklLZHIvWFhQcjhjNnpuenJQcHhkQWtGWTR3M0w1WS95clJKbzFUa3YwNU94Q2thUTR4WGRpYlhiClFQZU8rNm5yYXRWSVhQY09sTDN3OE1SbjE5KzBvRG9LRWU4SXozd1k1Zi9FTTFVYmVrdll5aUVtM1Jma3lkT1EKajZoY0tUeEwydEVRWjVSdnRSRlZZNTRuTXRBQjZlTGppVWdacVgvQVdKREhrTTJYM3JXc2VFcnlQZllEcmhCegpKRm5nRktGc2tiOTg0QU5GdXlQT2YxeGtWSXoySndIbVVUTzVFVlR1WjNXU2d4NkQvK1R4RG8zNWpvMGJoVnZxCmpCellUNDExclRLMUl3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRTBEQ0NBN2lnQXdJQkFnSUJCekFOQmdrcWhraUc5dzBCQVFzRkFEQ0JnekVMTUFrR0ExVUVCaE1DVlZNeApFREFPQmdOVkJBZ1RCMEZ5YVhwdmJtRXhFekFSQmdOVkJBY1RDbE5qYjNSMGMyUmhiR1V4R2pBWUJnTlZCQW9UCkVVZHZSR0ZrWkhrdVkyOXRMQ0JKYm1NdU1URXdMd1lEVlFRREV5aEhieUJFWVdSa2VTQlNiMjkwSUVObGNuUnAKWm1sallYUmxJRUYxZEdodmNtbDBlU0F0SUVjeU1CNFhEVEV4TURVd016QTNNREF3TUZvWERUTXhNRFV3TXpBMwpNREF3TUZvd2diUXhDekFKQmdOVkJBWVRBbFZUTVJBd0RnWURWUVFJRXdkQmNtbDZiMjVoTVJNd0VRWURWUVFICkV3cFRZMjkwZEhOa1lXeGxNUm93R0FZRFZRUUtFeEZIYjBSaFpHUjVMbU52YlN3Z1NXNWpMakV0TUNzR0ExVUUKQ3hNa2FIUjBjRG92TDJObGNuUnpMbWR2WkdGa1pIa3VZMjl0TDNKbGNHOXphWFJ2Y25rdk1UTXdNUVlEVlFRRApFeXBIYnlCRVlXUmtlU0JUWldOMWNtVWdRMlZ5ZEdsbWFXTmhkR1VnUVhWMGFHOXlhWFI1SUMwZ1J6SXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzU0TXNRMUs5MnZkU1RZdXN3WkxpQkNHekQKQk5saUY0NHYvejVsejQvT1l1WThVaHphRmtWTFZhdDRhMk9EWXBET0QybHNtY2dhRkl0TXpFVXo2b2pjbnFPdgpLLzZBWVoxNVY4VFBMdlEvTUR4ZFIveWFGcnpETjVaQlVZNFJTMVQ0S0w3UWpMN3dNRGdlODdBbStHWkhZMjNlCmNTWkhqemhIVTlGR0hiVGozQURxUmF5OXZISFpxbThBMjl2Tk1EcDVUMTlNUi9nZDcxdkN4SjFnTzdHeVE1SFkKcEROTzZyUFdKMCt0SllxbHh2VFYwS2F1ZEFWa1Y0aTFSRlhVTFNvNlB2aTR2ZWt5Q2dLVVpNUVdPbER4U3E3bgplVE92RENBSGYramZCRG5DYVFKc1kxTDZkOEVieUhTSHlMbVRHRkJVTlV0cFRydzcwMGt1SDl6QjBsTDdBZ01CCkFBR2pnZ0VhTUlJQkZqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQi93UUVBd0lCQmpBZEJnTlYKSFE0RUZnUVVRTUs5SjQ3TU5JTXdvalBYKzJ5ejhMUXNnTTR3SHdZRFZSMGpCQmd3Rm9BVU9wcUZCeEJuS0xidgo5cjBGUVc0Z3daVGFEOTR3TkFZSUt3WUJCUVVIQVFFRUtEQW1NQ1FHQ0NzR0FRVUZCekFCaGhob2RIUndPaTh2CmIyTnpjQzVuYjJSaFpHUjVMbU52YlM4d05RWURWUjBmQkM0d0xEQXFvQ2lnSm9Za2FIUjBjRG92TDJOeWJDNW4KYjJSaFpHUjVMbU52YlM5blpISnZiM1F0WnpJdVkzSnNNRVlHQTFVZElBUS9NRDB3T3dZRVZSMGdBREF6TURFRwpDQ3NHQVFVRkJ3SUJGaVZvZEhSd2N6b3ZMMk5sY25SekxtZHZaR0ZrWkhrdVkyOXRMM0psY0c5emFYUnZjbmt2Ck1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUlmbXlURU1nNHVKYXBrRXYvb1Y5UEJPOXNQcHlJQnNsUWo2WnoKOTFjeEc3Njg1Qy9iK0xyVFcrQzA1K1o1WWc0TW90ZHFZM014dGZXb1NLUTdDQzJpWFpEWHRId2xUeEZXTU1TMgpSSjE3TEozbFh1YnZER0dxditRcUcrNkVucmlEZmNGRHprU25FM0FOa1IvMHlCT3RnMkRaMkhLb2N5UWV0YXdpCkRzb1hpV0pZUkJ1cmlTVUJBQS9OeEJ0aTIxRzAwdzlSS3B2MHZIUDhkczQycE0zWjJDenFycHYxS3JLUTBVMTEKR0lvL2lrR1FJMzFiUy82a0ExaWJSckxEWUdDRCtIMVFRYzdDb1pERHUrOENMOUlWVk81RUZka0tycWVLTSsyeApMWFkySnR3RTY1LzNZUjhWM0lkdjdrYVdLSzJoSm4wS0NhY3VCS09OdlBpOEJEQUIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRWZUQ0NBMldnQXdJQkFnSURHK2NWTUEwR0NTcUdTSWIzRFFFQkN3VUFNR014Q3pBSkJnTlZCQVlUQWxWVApNU0V3SHdZRFZRUUtFeGhVYUdVZ1IyOGdSR0ZrWkhrZ1IzSnZkWEFzSUVsdVl5NHhNVEF2QmdOVkJBc1RLRWR2CklFUmhaR1I1SUVOc1lYTnpJRElnUTJWeWRHbG1hV05oZEdsdmJpQkJkWFJvYjNKcGRIa3dIaGNOTVRRd01UQXgKTURjd01EQXdXaGNOTXpFd05UTXdNRGN3TURBd1dqQ0JnekVMTUFrR0ExVUVCaE1DVlZNeEVEQU9CZ05WQkFnVApCMEZ5YVhwdmJtRXhFekFSQmdOVkJBY1RDbE5qYjNSMGMyUmhiR1V4R2pBWUJnTlZCQW9URVVkdlJHRmtaSGt1ClkyOXRMQ0JKYm1NdU1URXdMd1lEVlFRREV5aEhieUJFWVdSa2VTQlNiMjkwSUVObGNuUnBabWxqWVhSbElFRjEKZEdodmNtbDBlU0F0SUVjeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdjNGaQpDUEg2V1RUM0c4a1lvL2VBU1ZqcElvTVRwc1VnUXdFN2hQSG1oVW1mSityMmhCdE9vTFRiY0pqSE1nR3hCVDRIClR1NzArazh2V1RBaTU2c1pWbXZpZ0FmODh4WjFnRGxSZStYNU5iWjBUcW1OZ2hQa3RqK3BBNFA2b3I2S0ZXcC8KM2d2RHRoa1VCY3JxdzZnRWxEdEdmRElOOHdCbUlzaU5hVzAyakJFWXQ5T3lIR0MwT1BvQ2pNN1QzVVlIM2dvKwo2MTE4eUh6N3NDdFRwSkppYVZFbEJXRWFSSUdNTEtsRGxpUGZyRHFCbWc0cHhSeXA2VjBldHA2ZU1BbzV6dkdJCmdQdExYY3d5N0lWaVF5VTBBbFluQVpHME8zQXFQMjZ4Nkp5SUFYMmYxUG5iVTIxZ25iOHM1MWlydUY5Ry9NN0UKR3dNOENldEpNVnhwUnJQZ1J3SURBUUFCbzRJQkZ6Q0NBUk13RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBUVl3SFFZRFZSME9CQllFRkRxYWhRY1FaeWkyNy9hOUJVRnVJTUdVMmcvZU1COEdBMVVkCkl3UVlNQmFBRk5MRXNOS1IxRXdSY2JOaHl6MmgvdDJvYXRUak1EUUdDQ3NHQVFVRkJ3RUJCQ2d3SmpBa0JnZ3IKQmdFRkJRY3dBWVlZYUhSMGNEb3ZMMjlqYzNBdVoyOWtZV1JrZVM1amIyMHZNRElHQTFVZEh3UXJNQ2t3SjZBbApvQ09HSVdoMGRIQTZMeTlqY213dVoyOWtZV1JrZVM1amIyMHZaMlJ5YjI5MExtTnliREJHQmdOVkhTQUVQekE5Ck1Ec0dCRlVkSUFBd016QXhCZ2dyQmdFRkJRY0NBUllsYUhSMGNITTZMeTlqWlhKMGN5NW5iMlJoWkdSNUxtTnYKYlM5eVpYQnZjMmwwYjNKNUx6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFXUXRUdlpLR0VhY2tlKzFiTWM4ZApIMnh3eGJodXZrNjc5cjZYVU9Fd2Y3b29YR0tVd3VOK00vZjdRbmFGMjVVY2pDSllkUWtNaUdWbk9Rb1dDY1dnCk9KZWt4U09UUDdRWXBnRUdSSkhqcDJrbnRGb2xmenEzTXMzZGhQOHFPQ2t6cE4xbnNvWCtvWWdnSEZDSnlOd3EKOWtJRE4wem1pTi9WcnlUeXNjUGZ6TFhzNEpsZXQwbFVJRHlVR0F6SEhGSVlTYVJ0NGJOWUM4blk3Tm11SERLTwpLSEFONHY2bUY1NkVENzFYY0xOYTZSK2dobE83NzN6L2FRdmdTTU8za3d2SUNsVEVyRjBVWnpkc3lxVXZNUWczCnFtNXZqTHliNGxkZEpJR3ZsNWVjaEsxc3JEZE1adk5oa1JFZzVMNHduM3FrS1FtdzRUUmZaSGNZUUZIZmpEQ20Kcnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlFQURDQ0F1aWdBd0lCQWdJQkFEQU5CZ2txaGtpRzl3MEJBUVVGQURCak1Rc3dDUVlEVlFRR0V3SlZVekVoCk1COEdBMVVFQ2hNWVZHaGxJRWR2SUVSaFpHUjVJRWR5YjNWd0xDQkpibU11TVRFd0x3WURWUVFMRXloSGJ5QkUKWVdSa2VTQkRiR0Z6Y3lBeUlFTmxjblJwWm1sallYUnBiMjRnUVhWMGFHOXlhWFI1TUI0WERUQTBNRFl5T1RFMwpNRFl5TUZvWERUTTBNRFl5T1RFM01EWXlNRm93WXpFTE1Ba0dBMVVFQmhNQ1ZWTXhJVEFmQmdOVkJBb1RHRlJvClpTQkhieUJFWVdSa2VTQkhjbTkxY0N3Z1NXNWpMakV4TUM4R0ExVUVDeE1vUjI4Z1JHRmtaSGtnUTJ4aGMzTWcKTWlCRFpYSjBhV1pwWTJGMGFXOXVJRUYxZEdodmNtbDBlVENDQVNBd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFTgpBRENDQVFnQ2dnRUJBTjZkMStwWEdFbWhXK3ZYWDBpRzZyN2QvK1R2Wnh6MFpXaXpWM0dnWG5lNzdadEo2WENBClBWWVlZd2h2MnZMTTBEOS9BbFFpVkJEWXNvSFV3SFU5UzMvSGQ4TStlS3NhQTdVZ2F5OXFLN0hGaUg3RXV4NncKd2RoRkoyK3FOMWozaHliWDJDMzJxUmUzSDNJMlRxWVhQMldZa3RzcWJsMmkvb2pnQzk1LzVZMFY0ZXZMT3RYaQpFcUlUTGRpT3IxOFNQYUFJQlFpMlhLVmxPQVJGbVI2allHQjB4VUdsY21JYllzVWZiMThhUXI0Q1VXV29yaU1ZCmF2eDRBNmxOZjRERCtxdGEvS0ZBcE1vWkZ2Nnl5TzllY3czdWQ3MmE5bm1ZdkxFSFo2SVZEZDJnV01aRWV3bysKWWloZnVrRUhVMWpQRVg0NGRNWDQvN1Zwa0krRWRPcVhHNjhDQVFPamdjQXdnYjB3SFFZRFZSME9CQllFRk5MRQpzTktSMUV3UmNiTmh5ejJoL3Qyb2F0VGpNSUdOQmdOVkhTTUVnWVV3Z1lLQUZOTEVzTktSMUV3UmNiTmh5ejJoCi90Mm9hdFRqb1dla1pUQmpNUXN3Q1FZRFZRUUdFd0pWVXpFaE1COEdBMVVFQ2hNWVZHaGxJRWR2SUVSaFpHUjUKSUVkeWIzVndMQ0JKYm1NdU1URXdMd1lEVlFRTEV5aEhieUJFWVdSa2VTQkRiR0Z6Y3lBeUlFTmxjblJwWm1sagpZWFJwYjI0Z1FYVjBhRzl5YVhSNWdnRUFNQXdHQTFVZEV3UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUZCUUFECmdnRUJBREpMODdMS1BwSDhFc2FoQjR5T2Q2QXpCaFJja0I0WTl3aW1QUW9aK1llQUVXNXA1SllYTVA4MGtXTnkKT083TUhBR2pIWlFvcERIMmVzUlUxL2JsTVZnRG9zek9ZdHVVUlhPMXYwWEpKTFhWZ2dLdEkzbHBqYmkyVGM3UApUTW96SStnY2lLcWRpMEZ1RnNrZzVZbWV6VHZhY1BkK21TWWdGRlFscTI1emhlYWJJWjBLYklJT3FQakNEUG9RCkhteVc3NGNOeEE5aGk2M3VneXVWK0k2U2hISTU2eURxZysyRHpaZHVDTHpyVGlhMmN5dmswL1pNL2laeDRtRVIKZEVyL1Z4cUhEM1ZJTHM5UmFSZWdBaEpobGRYUlFMSVFUTzdFckJCRHBxV2VDdFdWWXBvTno0aUN4VElNNUN1ZgpSZVlObnlpY3Nia3FXbGV0TncrdkhYL2J2Wjg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: c2VjcmV0c3RvcmU6cmttczozYkRMT2lrVFFUMmlQUGpxWTBSZHh0Y2I4TjI1SFlNdzlCa3FaR1NkQjUvaGp4dllqOGpKck8wZThzZVZnT1VlaEwrUzc4YzlkS0pUNjZWdWVyTTlSL25WM2FaajR5bi9iMjBLRDVxWHRGRGhXMUp1NjJZVjB6QlZLN3B1VmROS1JXL3d0bnlEYlU3ZlhOVWpyc2hSc1g1WitQSDZQcHZmb0ZzMEcra0dLRmdBUDRBYk9YZ2VQVmhaTVdxQU54NmxpVFhvWkZUa3NxT1BaVHB2UUNJSEc2TlBRV3UvTWVkZlVQdGFtYTgrYm5JYXVSQlZaeDFZN3FoYkYzR3BVd3JIMVMwbnJLYlJpY2NPeVFDZkNucGpDSUJJRk9HYlNxSXM5eUkvaTYvWnJSb2J5bmdqblVHU005dE45VzZqaStHajlobEdxYU1vRVZSbzN2WXJyNTFxZU9sMWlwbldEY2FJMnF3YzBCMDllQW1QYm1yeG1ob0xhNHdUVjJRSkpJTU1aOGZvRGRjL082MjdJZ0xIWklWcCsvb0hKRytCOW9KZDFqelRNTFI1Mm14NE1kUnZoVHVvdFFLTmNNQmErRXVZQ3BTdXZjZElRVkthVnlBcHlUUEpabkRXMjZYekJ2QjdSb3F0alBCZTJ2ZVhsQmx5bGZCb0tpZk15U2puYmVDemhNU3ZJb0xJVjNmWGV5R1N6aUpRakZUTFozOEVPZXNSMDQ3bVZXengrRy9KemNZNFVnc2pEb1VUQXEvaksyR0hlRzdZbXNoUkt4Mkc5cGJITkZmSU9yUWYwdnZidGhBMTRCdVpNaldFUGdMNm81NjNxSXU1eXVPM2xUQ0xwSGRYK2xKZ0Y5NXh3SW5ycjgrUHBJRGRFNWZ3NEw4c1ZZc095cjNKZWxJajdVNTR2Njg1cFYyNFBlNDNNUzkzOGRubjdIRlZmRnJVaXd5MEdPalZwdjlOWWw3N1hxY1k0UXplWDZTM0Rib25yK0txaDg1ZVFlMmtobk5hNTJ4TGZuTitxRXJlTHBvU2pzZjZ5eXpLZGtuMzJwT2xCbTZBQkFyVmVaOFA2QXN0Wmd5d1gvM2pqNVU2TWdPMTZJZ1d1UkpqUjNwcG9XU09SQUozZ2ZWMmlDbVloMTRmVUx4cUNML3l4QUFDV2ZIaHFsQnhIVEU1QXg5RHpVTzVqUFpacVBsVHNkWGRqalc0ZFVsR2VOd0EyMkRoRUFzdHJ1Rk5aWmwxWG9mck9iS0k5UUJhMDRCT1ZnSHNqVG94K1UrSzQrUnUxdzQyUlFrcEhZWFQ3bnc4S3I5eFd1aUhZN2UyRDYxRUZsdzJoY3hoaHhHN3JHK25IZHdaSXJNcTJIbk9CcnJ2TnFuRWFnMVN5ODUwaGVOM1pIU0I2eDU5bHF0OE5aYkFLMmVjWUFkMkwxMGhBUHRwZnZrZXgxKzJuTlMvbUVROTNlOFJFaGJFNGNhOGl3dTZCcExXVXlCeWdJdEtscisxay91R2FUMEM5NnlGUHVWUWJFRE52M1JrNUt1S3RXaU9XTksyK0hOTlpuRlIvYlRhemloTG9tOGJXZm5Pc3k2ck8xQjdudkxLUTlqRmRmTWRHZ3crdlIrUU9mV2thdyswWk9TUVQ0aHZ6RGE0SFptTTBPZVFpeHVtUGg4US83RElBZ0M2Mit5bG1ZbHA5eVo5K2daYnY2cUVVNW92NnFENStUNDVSTFFWL0dnRzNwWU9hQUxIcDVQVkNsWjJGbnAvci9ENXE2U1JvNkZMb0Q1NkFmaGgyaHJ0YU5Ca1hTOGtwMERNMXF0dlhCMkVkOHZueGlQOFVyWnBKSHV4amdrdXdjRndtVW9PN1RQTTJpZjFyNEdyZ3F3b2F5RjNIL0tXcU9maHBGOWNsTS9GYWlPLzNmVHAxczVmUWI3Y3dlNlYvQS9rRGVlZ2NjTEZqenEzNGN0QnZJWkpIL1NPM3VkcHhRTTNZcFdpZWhZeExhdjRXbHBPYXFINVRCN0ptNUg1U1NVdytsQWxibG1uRWU2S2Z5OWVBS0Zuc1F4Wjg1NkZUK1VvanlNZnRkRTBHU3B4eWhvT3JySy9Cb2Z5ZkNIUjdPcHRYcUNrd3JKUktWVWRnSXZjelJyYkFMVVZ4R3J0eTBQaXh6VGkwUTM2WjJSaVhJbGw0ZHNWdTlXWWltdWIyTmNUb2c2b0N5Z1VuODFxSzNWb1FwNjM3K2lnS1lDTU1vZzd5WHBMOW9qd0JJZDRFMFBkczlBaXhrUW8yaURJL2NTVU9ObEYwaFlqaytSUG5kWHZqeFVldEhVYzVENzM1T2Y0amZVV0dmT1NGbVMyV0VjbUJKZVl1ZUNKKyt5ZEpqQ1RxTmYzSXBKekJ4dFZuczgyZDVJUC8yMUNJUlhZMkhuaUljK2NZQzkrMnQzUmZzamtMd1ovbFpQSHF4YWYvR1lNRitrdXNybk1wak41RnE5MXF1QmI3MmhIV25TM1NzWC9zRkQrZVEybEJ5NnEwaVgyYlRyOUxHQ0lFZ3hqZTUzVkY5MkdVRURmWURuMjhSQ2NZbXc3cWtWeDRRM3VsTjlkQUVEcmpYdHQyWC9QQVgrQzZzRnhkZFZKSWVjaXBqSURWcEZYMVBzRk9tdWV1NU14MEVCYmpkMFFsNVJQQXVIQkgwMEdva2FrU0tIWnQrOFVVTlQvZWhxd0VjRmRtdGY4QlcrQkxtS1o2RU93Tm5OaTZMeTRJNUVIdVlGVEZ3ZDhialhuWFBmeG1lWHRzcFBzNDFOUE9KUW4rZG4rL0p3ZHQ0aWwrSnE4Z1Z6VXdFOGM0QzNhWFN6U21ZV0YxeUZVQkhWZmlpUW9xS2dUOFgyQ251MWduYjRmQUlVWC9xbmh0dnlxRmFQejZWdVk1ZzZLNzN3R2xrWnh6UkRCZFlIZmhXY2NVTVFSekZPRUhURlJBMWMveW5lMVJWOFc2SGNQK3FkVFFHa0w1TDJGZjVLZmdLeU81anEvWmlTbldMSDNTUUpWd3pvYVFkU2xrTGVPREtjNmNFQ051ZitPekwyNGFtMVE4Sms9
kind: Secret
metadata:
  annotations:
    rafay.dev/secretstore: rkms-secrets
  labels:
    rep-organization: 5m18rky
    rep-partner: rx28oml
    rep-version: rx28oml
    rep-workload: kvq9ov2
  name: kvq9ov2-new-worklo-4145937496-ingress
  namespace: ns-1
type: kubernetes.io/tls

---
apiVersion: v1
kind: Service
metadata:
  labels:
    rep-container: kvq9ov2-new-deploy
    rep-organization: 5m18rky
    rep-partner: rx28oml
    rep-version: rx28oml
    rep-workload: kvq9ov2
  name: new-deploy
  namespace: ns-1
spec:
  ports:
  - name: port-80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    rep-app: new-deploy
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    rafay.dev/registry-29967y2: gajanan-acr
  labels:
    rep-app: new-deploy
    rep-organization: 5m18rky
    rep-partner: rx28oml
    rep-workload: kvq9ov2
  name: new-deploy
  namespace: ns-1
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 300
  selector:
    matchLabels:
      rep-app: new-deploy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        rep-app: new-deploy
        rep-organization: 5m18rky
        rep-partner: rx28oml
        rep-workload: kvq9ov2
    spec:
      containers:
      - args: []
        command: []
        env: []
        envFrom: []
        image: gajanantest.azurecr.io/hello-openshift:latest
        imagePullPolicy: IfNotPresent
        name: new-deploy
        ports:
        - containerPort: 80
          name: port-80-tcp
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 1024Mi
          requests:
            cpu: 237m
            memory: 972Mi
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      tolerations: []

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    rep-organization: 5m18rky
    rep-partner: rx28oml
    rep-version: rx28oml
    rep-workload: kvq9ov2
  name: new-deploy
  namespace: ns-1
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: new-deploy

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/configuration-snippet: set $workload_name "acr-workload-wizard";set
      $workloadId "kvq9ov2";set $orgId "5m18rky";set $partnerId "rx28oml";
    rafay.dev/dns: 'true'
  name: kvq9ov2-new-workload-wizard-acr-http
  namespace: ns-1
spec:
  rules:
  - host: new-workload-wizard-acr.run.rafay-edge.net
    http:
      paths:
      - backend:
          service:
            name: new-deploy
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - new-workload-wizard-acr.run.rafay-edge.net
    secretName: kvq9ov2-new-worklo-4145937496-ingress
