kind: ManagedNamespace
apiVersion": "config.rafay.dev/v2"
metadata:
  name: chari-ns-chart
  description:
  labels: 
    dev/test: "true"
    component: "namespace"
  annotations: 
    a1: "value"
    a2: "v2"
spec:
  psp:
  type: RafayWizard
  resourceQuota:
    limits.cpu: "10"
    limits.memory: "10G"
    requests.cpu: "3"
    requests.memory: 1G
    fromFileContent: |
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: object-counts
      spec:
        hard:
          configmaps: "10"
          persistentvolumeclaims: "4"
          pods: "4"
          replicationcontrollers: "20"
          secrets: "10"
          services: "10"
          services.loadbalancers: "2"
          requests.cpu: "1"
          requests.memory: 1Gi
          limits.cpu: "2"
          limits.memory: 2Gi
          requests.nvidia.com/gpu: 4
     
  limitRange:
    limits:
      - type: "Pod"
        max:
          cpu: "2" 
          memory: "1Gi" 
        min:
          cpu: "200m" 
          memory: "6Mi" 
        default:
          cpu: "300m" 
          memory: "200Mi" 
        defaultRequest:
          cpu: "200m" 
          memory: "100Mi" 
        maxLimitRequestRatio:
          cpu: "10" 
      - 
        type: "Container"
        max:
          cpu: "2" 
          memory: "1Gi" 
        min:
          cpu: "100m" 
          memory: "4Mi" 
        default:
          cpu: "300m" 
          memory: "200Mi" 
        defaultRequest:
          cpu: "200m" 
          memory: "100Mi" 
        maxLimitRequestRatio:
          cpu: "10" 
    fromFileContent: |
      apiVersion: "v1"
      kind: "LimitRange"
      metadata:
        name: "limit-range-sample" 
      spec:
        limits:
          - type: "Pod"
            max:
              cpu: "2" 
              memory: "1Gi" 
            min:
              cpu: "200m" 
              memory: "6Mi" 
          - type: "Container"
            max:
              cpu: "2" 
              memory: "1Gi" 
            min:
              cpu: "100m" 
              memory: "4Mi" 
            default:
              cpu: "300m" 
              memory: "200Mi" 
            defaultRequest:
              cpu: "200m" 
              memory: "100Mi" 
            maxLimitRequestRatio:
              cpu: "10" 
  placementPolicies:
    label_selectors:
    - key: rafay.dev/clusterName
      value: avinash-eks
    drift_action: NotSet
    selector_context:
      placementPolicyType: Labels


resourceQuotaEnabled: true
limitRangeEnabled: true