apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: madhu-bp1-v3
  project: defaultproject
spec:
  base:
    name: default
    version: 1.12.0
  customAddons:
  - name: asd
    version: v1
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    enableVM: false
    monitoring:
      helmExporter:
        discovery: {}
        enabled: true
      kubeStateMetrics:
        discovery: {}
        enabled: true
      metricsServer:
        enabled: true
      nodeExporter:
        discovery: {}
        enabled: true
      prometheusAdapter:
        enabled: true
      resources: {}
  drift:
    enabled: false
  sharing:
    enabled: false
  version: v5
