apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  description: ergrw
  name: wegeg
  project: defaultproject
spec:
  base:
    name: default
    version: snapshot - 2022-02-25T04:04:51Z
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  sharing:
    enabled: false
  version: swgr
