apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: acr-native-yaml
  project: aniruddha-prj
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/acr-native-yaml/acr-native-yaml.yaml
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: new-ns
  placement:
    selector: rafay.dev/clusterName=qc-gajanan-eks
  version: acr-native-yaml-v1
