apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: helminhelm
  project: aniruddha-prj
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/helminhelm/nginx-9.5.4.tgz
      valuesPaths:
      - name: file://artifacts/helminhelm/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  drift:
    enabled: false
  namespace: new-gaj-ns-1
  placement:
    selector: rafay.dev/k8sVersion=v1.22.2,rafay.dev/kubevirt=disabled,env=dev
