apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: helminhelm-1
  project: aniruddha-prj
spec:
  artifact:
    artifact:
      chartName: nginx
      chartVersion: 9.5.4
      repository: default-bitnami
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  drift:
    action: Notify
    enabled: true
  namespace: gajanan-ns
  placement:
    selector: rafay.dev/clusterName in (gaj-nodetest-mks,hardik-qc-mks-2)
  version: helminhelm-1-v1
