apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: new-workload-helmingit-4
  project: aniruddha-prj
spec:
  artifact:
    artifact:
      chartPath:
        name: working-helm/helm-multi-values/nginx-8.2.0-rafay.tgz
      repository: gajanan-test
      revision: main
      valuesPaths:
      - name: working-helm/helm-multi-values/nginx-values-1-with-rauto-automation-ecr-registry.yaml,working-helm/helm-multi-values/nginx-values-3-with-rauto-automation-ecr-registry.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  drift:
    enabled: false
  namespace: gaj-ns
  placement:
    selector: rafay.dev/clusterName=hardik-qc-mks-2
  version: v1
