apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: new-bp-helm
  project: defaultproject
spec:
  base:
    name: default
    version: 1.12.0
  customAddons:
  - name: test
    version: v1
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  opaPolicy: {}
  placement: {}
  sharing:
    enabled: false
  version: v1
