apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gajanan-test
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCKmG7XBpEL3Vg3bPJltBKrvd6BeXeJHVMwwdIinyTWXDIP/zxA3A7ARr5w1NymG/tmRkJS8jqb0Q4a/aKURjrF/UsfZF/m0Fg6oheJNGg8mjI3FQ5i2VcLaeXTMYBcZZRdQFBlsIoHpEP/i2o32dVhBuGzxVHf634lzVlKPWv7aBBUjdliDXq56Q/GrBugtUbkhfYF//pI2St8yd6XQmlv6SqmNKHTRcO6MbJ4D6s9apfCH1cr2RBtS+Ir+aA/lC9xQourxpdrtnisYHX7sycmAQwup81grK6zDvjVFvu9gXH0QWePxjRDvmv3WmICbJymJqw2GlsP6Qu5buCVtFEgrBTXWSED9PdB12PYZAiTo+Jkv1RAk1UnVSYH/LGKqH38211y/HQyI6XFDlbGktyIX0idqEt6Yz4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gajanan-test
      namespace: default

