apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gajanan-test
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCpGEPsupTm5iOvpf9fHyCRqC/YSi2Nj4CFBflpIvBW2vCDSPq/ocbh21HtUw2GJxLnP+VusatuASIOBg0Vuy9lKG3TaVyXrcq+1k67LZzLqB2F5pPn2KBRtz7sD7YEQDiKEzQQFiRYafZEfdVp7Q4Huv7oe0TTqDWl1ELiZR0meicjWleV2dNGGkWgE0VbMkdyHJkAi0aDHivfHzz8CFl1M+I2jRiqAqv8me1sZfBRul3xP69BIvyh0jyagxr4HBdFYmEgTfYncRm80ehi11DlMM8J/rAamaLjRx2/b6L+hbejyGPCU1AnO/MGR/YjgqU0iOBhvc2uSfxtMVzr2QlgMyV+N8EP52WTNoogVc2iGKoqsMO8+/3p6stjC4cGwI0yRg0BGuaRUCj/+kVTMVuNkJxvbQzCILM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gajanan-test
      namespace: default

