apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gajanan-test
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAUGxlsomb3h8XSAZzqyodM8JZiH6n42a5tknE6OqRkLRcOhGRP+qUfqedmEcGce36bVXbgGtWezExy2vozkuPWWfym1xhsWyUBgu5RDHMaJT8xspvkQcUjKnRV9E0UN+EhtzdLYuxe6Jxan3Ol3Hyy/JlAgWBcTNicOYJ16QRrx+OTIowvUe33v8vPjODJEqdfI85v0iG3oK3iZVJUg5Re+beq/RqP/LhobuhGJ0JWoa0tvi8g+dKmbXJGUr/x9o4MuAsjVjMprXJjVNDlHBNykqF6yntGWnB3xIyPIdG9U6Qp+shC76TNjf2FiznU9FbtepSm4zNOrY6ckKiQ9JANSp6cTmRBITFQI+EDmyVZ8MVVI/aOqQJ1Xo27oF/Xg+9muwo1HrECWpN3izT25Mid+NdMNmD7C88=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gajanan-test
      namespace: default

