apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gajanan-test
  namespace: default
spec:
  encryptedData:
    credentials.password: AQANNZ3/6mKlUWZKHodHohhdsP4SAl9BJVLZBOjezsJtrxqB74mYN765d/qdZkxQe3bnLvz5q93Md2WksHqRkMGfh5xQ3qIHmqCRa6YXlPIkSQoQ/wTpDS/wvBJkM2IB1fuT3beRM8YQHBjkWOtfcK0yus0RZNUTZohLQgtXFE9luz321upVYaaET5Ujqfw9jk4k8+hPTwxsKA7RVJEt65w4hjRwmuGjz6KG3vGIhqe2fBbV6QdQEhu7bhKK9Z9yln7/2TgssuUj6mNvZ0jKIPVlGqOHfRcOWzcbccELCbF6ffb6uplek1a6Cnf7G6hvxcouP//J6SH1CytQiKIqamAoDBMgvV0daRSJcB5w9P83VnMTSQdVJKYojtHjZolbOs8fi4nJlBNNHxyfBiMvrD3tzb1R2yewD94=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gajanan-test
      namespace: default

