apiVersion: integrations.k8smgmt.io/v3
kind: SecretStore
metadata:
  name: new-secretstore-sanity
  project: gajanan-prod-test
spec:
  config:
    vault:
      clusters:
      - authPath: test-path
        clusterName: prod-gajanan-mks-2ndapril
      host: https://gajanan-vault-prod.dev.rafay-edge.net
  provider: Vault
