apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: test
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/test/nginx-9.5.4.tgz
      valuesPaths:
      - name: file://artifacts/test/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: gajanan-ns
  sharing:
    enabled: false
  version: v1
