apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: test
  project: defaultproject
spec:
  artifact:
    artifact: {}
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: gajanan-ns
  sharing:
    enabled: false
