apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gajanan-test
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCtlGt68wvjUvNaKeAxj31d3nG/lzJdNjShAyLkBp8/ReGjv/fOXQbtswcxjshi9KKQHjZGE+3qr2ORk0iaOuO9O1tcY0RPtdzJgaHVp5tkpT3L12wvFWInti+QaFIhLTsnTT+TCL+/7nGQpItLJicRtnYcghh1L/IHgU/FUTA6YS+dhBFAgXq7ZmbDc2CsIgVpdeDMI4aqNQgedcmHzuam84S08rgY6PYmUAp9BSvELqncgMFW9ESm7Si6ll52G8wCOwAdGopxpCEDsz/kp0cZFnoDLJkUfFJLs+UyaMTfiOj7btSSNWeVD8uSxY/ebjyG0WgfYw2vPETDppASWf/e2T3tBtztstgy6ndWVpH+ltEIwKMsw+IDEywdIzlE3L4C6u7EiiBziMasKpQQerQJcstJjawIrGg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gajanan-test
      namespace: default

