apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gajanan-test
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBi2oE9BtESrg0YZfV6cj+Cc3fqHmd65bHl9C0CP2Nwiso/sKGApBmmd5UMk9AWFvl0qFJ9B5y5zqyWeu21vAt5KuySHCkGiIQ1VhhvIjkqG1fYJM9Wwwuul+LXeLwp/+EQqY/7oPyKO8gRuDLDcfkAg/WgrWHe1bIkMqs5hJ+6EwE6PChHU5ePpoJGcIBpdfgFk+9xg1/N7tk4mfIXK0rNA+WSg+BfUwdI5C/Mlmp3tRgN4JD/3rdlEJ1Q6xWRDrfDL/AcgeDQRK8iXj5PyXXzKTVVJuLj2mC96u5m/89L/3hrP729drHvSoHy0GmQPX1Iyw69jnp4sO3JXgamrdLeJmG69KuipAPEPEXCviM6zjnG+XyhHVuyj+METpaFFGQicEVYKusyE8uxUfebiXIHjEO0IoHOjZs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gajanan-test
      namespace: default

