apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: asd
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/asd/nginx-workload.yaml
    options: {}
    type: Yaml
  namespace: tb98ns01
  sharing:
    enabled: false
  version: v1
