apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: asd2
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/asd2/nginx-9.5.4.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: tb98ns01
  sharing:
    enabled: false
  version: v1
