apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: a
  project: aniruddha-prj
spec:
  artifact:
    artifact: {}
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: ns-name1
  sharing:
    enabled: false
