apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: avinash
  project: aniruddha-prj
spec:
  artifact:
    artifact:
      chartName: nginx
      repository: default-bitnami
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: new-ns
  sharing:
    enabled: false
  version: v15
