apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: new-addon-helminhelmrepo
  project: aniruddha-prj
spec:
  artifact:
    artifact:
      chartName: jenkins
      repository: default-bitnami
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: gaj-ns
  sharing:
    enabled: false
  version: v1
