apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: new-rctl-addon-yamlingit
  project: aniruddha-prj
spec:
  artifact:
    artifact:
      paths:
      - name: working-yamls/nginx-workload.yaml
      repository: gajanan-test
      revision: main
    options: {}
    type: Yaml
  namespace: new-rctl-addon-ns
  sharing:
    enabled: false
  version: v1
