apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: new-addon-nativeyaml
  project: aniruddha-prj
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
  namespace: gaj-ns
  sharing:
    enabled: false
  version: v0
