apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: default-rafay
  project: defaultproject
spec:
  drift:
    enabled: false
  limitRange:
    container: {}
    pod: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: gajanan-tb-mks-co
  resourceQuotas: {}
