apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tb98repo01
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCtT49e5C+k6L1DIg/kG5eAnlpHLncadVK8qHakYVsfjskH2URgK92YiDst/yQRdNrfMn0IigygSi1zWUmigqORqGdiWKwPFcQ35meniHQxxcuo10jMJn+eobjFfuZDFLEpE/026I/l1wevhu896sWb7txtlSfv/KT2My6jWZrk8tr11/mQPbAGQ7YsNj93caejPlpUD+uxP/nXJCn9wzizZb+dprFg5DSCoYToIJIkEXEUKtVExW914qq0Ok3sn/7QUI+Ch4Vf1Abp69N3TsiQp3kwo8+tBpLXooLkdVydDil7BvrJdogMEnLiES2FUxBjJTs6zs4YkBvojIBlaP3amA76TJLz5tWmo/YKfajwsWQBVtJOISv58T7nIo+MzifSWBU14osqPkQIB5s3cyGUPCuEBoKBwpo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: tb98repo01
      namespace: default

