apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: gaj-ns-2
  project: aniruddha-prj
spec:
  drift:
    enabled: false
  limitRange:
    container: {}
    pod: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: gajanan-test-rctlv3
  resourceQuotas: {}
