apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: new-ns
  project: aniruddha-prj
spec:
  drift:
    enabled: false
  limitRange:
    container: {}
    pod: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: gajanan-qc-eks
  resourceQuotas: {}
