apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: new-gaj-ns-1
  project: aniruddha-prj
spec:
  drift:
    enabled: false
  limitRange:
    container: {}
    pod: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: hardik-qc-mks-2
  resourceQuotas: {}
