apiVersion: integrations.k8smgmt.io/v3
kind: SecretStore
metadata:
  name: new-vault-secretstores-121
  project: defaultproject
spec:
  config:
    vault:
      clusters:
      - authPath: test
        clusterName: tb103cl01
      host: https://gajanan-vault-testbed.dev.rafay-edge.net
  provider: Vault
