apiVersion: integrations.k8smgmt.io/v3
kind: SecretStore
metadata:
  name: test1
  project: defaultproject
spec:
  config:
    vault:
      clusters:
      - authPath: test
        clusterName: test
      host: asdfgdfgd
  provider: Vault
