apiVersion: integrations.k8smgmt.io/v3
kind: SecretStore
metadata:
  name: test2
  project: defaultproject
spec:
  config:
    vault:
      clusters:
      - authPath: test
        clusterName: tb103cl01
      host: asdgfasdf
  provider: Vault
