apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: test-addon
  project: defaultproject
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
  namespace: default-rafay
  sharing:
    enabled: false
