apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gajanan-test
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCY53fzShaixAxX6FzPXVNSEvEk9M+VyQJxkQ8Fj0r0GJqrXuScu61tvMFwQlIxxFp8Kd2KpgyO6RnWK+JSjHDS77Ivlkd9vw2LcG7n4fcDv3q0cN05FaaF+/9dwbYwRO828EeM+wy1DWyILwxEsLmj0eNtD2ORHp+sEHQBG5Knw/w0lnzM7tjOb1FnRoFmzV09cvG2UC53aVODMfz85Uq+9SgX1671kcbIyKN1dQk/pBQr1cSCqjjbhZU6VSeZYD4Pmb6l0PwCWnZhVZOqRoJA2OrPApEr/RRjRLmJ0VvQlyudV4mN8pXEb5JngqHj58XK5v/3UM01wHgtofaV2uChYHl1dwJNeCwISkc33SSaRh+NiPH/fn843C6bfejldlIOisYUzvwVYkFdMLg+Ji41kygTaBCIHIY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gajanan-test
      namespace: default

