apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gajanan-test
  namespace: default
spec:
  encryptedData:
    credentials.password: AQB3A5HbAHm00Oen8DKDYHTWIHHAqiYBpLxpFkWSG0N8bv6ycdw8LkK0wGoXa3wm20cykRSZHhHWQPVD+aYVqrZT17lK7JE+lej6EH6Zu579THqmb/YKzMpJ3Iz2ldIipd8/VMQrPl+XT9hKrXKVlwQ45LXPU4BLOn8I2ieGJK/praQBRiTnWhoVXc+D5jAIUS91e/4sLMN1zBOdpBntjMmXkZlTurmaHJPSUxOway/LSmY/BOm2WjQYOllif2+KQOerDqcAVHxe7W3l0y6U5scI7erDOFdraBepJiu56hwKiUpu0SnVx0/BtZSyYTo326w3LXP4HzrKGlmbUJ5ELMvmLxpMq7DUWp5nx4Aw5kvwvbDEiVFeLUH8Q9VYYgWMlew2EnX7up3u8wouOHQUwupeCQwEK0/Iozo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gajanan-test
      namespace: default

