apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gajanan-test
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAlho6ObEwnwkki5T1dhcjeac4FQXjt6um7dJ1lMQ9DWF3+DSAh2w9JntNJ8ZT845ZrEQL8JsQDEiQg0pWCzzte+6J3o2PM3LyrE2KU9yygnGxcIW9F/iXpfzS0GSb/lztanmD32V0n/yRGPmAHK+ayZ82WBnShE8IhNUApAHmgxDu+fArVp2GsR7TSWBJOt9fBfscr3AhCiO1QVSl+59GNCfNu0WOg3oLUJMUB3qfQeiY7nhDEdZquXnNPC/CM1QUTQPZjTXsDUeGlU+919Gva1qVVou21JXSzi/PE2U61GfNaq6r3wWMKinpY4s6+z/c95CWjmITfQwQqnhucUkKyBKIyf0YE3cx7IMwhEjLelv9zATXH8YeD/tPyaNc8S5zBf5KMxmB01WmWCVo/1F0D43oYXgQn/i4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gajanan-test
      namespace: default

