apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gajanan-test
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCDxk9fPB0GonkXHjjRMB5YsdGLm1Xket4he4L6XeOZwxLRVvbuL4hARQwBuaEA+/ala0Q/DAcv/RFtSMg2cOTrUn5ss2vlFhDcyLnYCf/2yoRMY3NYYChnR8jpH2vX/xE1mDt4GXk2W4C/ojR+8YujeeabhLiOutVsyPB5lYM+bYachPfjq77LckgrRw3WevSNTnpvthR3sKYK2GI8JPiJIWXjmmm6cjAL5OJ4jiUVki601t+TKwilXdIvbBhoqVP2rv37k2reF7aTVWHLEhBUpwu5+w69zytPA5cicE/nCKVcZoBWNdTk1oXiO3b6+o2fZouVipiX+bdAbgwYBzlLpBmM0pmF6z+vczEaFm/EJoJzJE3gBwhZEHvbpHwBaMaBwm0D1sl6MLyMAk+RnHx7dJ5C7B+MUGQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gajanan-test
      namespace: default

