apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bp-v3-112
  project: gajanan-prod-test
spec:
  base:
    name: default
    version: 1.12.0
  customAddons:
  - name: new-addon-nativeyaml-v3-112
    version: v1
  - name: new-addon-yamlingitrepo-v3-112
    version: v1
  - name: new-addon-helminhelmrepo-v3-112
    version: v1
  - name: new-addon-helmingitrepo-v3-112
    version: v1
  - name: new-addon-helmchartwithvalues-v3-112
    version: v1
  - name: new-addon-helm3chartonly-v3-112
    version: v1
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    enableVM: false
  drift:
    action: Deny
    enabled: true
  opaPolicy: {}
  placement: {}
  sharing:
    enabled: false
  version: v2
