apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: new-acr-bp
  project: gajanan-prod-test
spec:
  base:
    name: default
    version: snapshot - 2021-12-11T06:24:32Z
  customAddons:
  - name: acr-new-addon-helm3
    version: v1
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  opaPolicy: {}
  placement: {}
  sharing:
    enabled: false
  version: v3
