apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: old-rctl-bp-postfix
  project: gajanan-prod-test
spec:
  base:
    name: default
    version: snapshot - 2021-12-23T05:19:04Z
  customAddons:
  - name: old-rctl-new-addon-yamlingit-postfix
    version: v1
  - name: old-rctl-new-addon-helmchart3-postfix
    version: v1
  - name: old-rctl-new-addon-helminhelm-postfix
    version: v1
  - name: old-rctl-new-addon-multivalueshelm-postfix
    version: v1
  - name: old-rctl-new-addon-nativeyaml-postfix
    version: v1
  - name: old-rctl-new-addon-alertmanager-postfix
    version: v1
  defaultAddons:
    enableIngress: false
    enableLogging: true
    enableMonitoring: false
    enableVM: false
  drift:
    enabled: false
  opaPolicy: {}
  placement: {}
  sharing:
    enabled: false
  version: v2
