apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: test-bp
  project: gajanan-prod-test
spec:
  base:
    name: default
    version: snapshot - 2021-12-23T05:19:04Z
  customAddons:
  - name: test-addon
    version: v2
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  opaPolicy: {}
  placement: {}
  sharing:
    enabled: false
  version: v2
