apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: gajanan-t
  project: gajanan-prod-test
spec:
  credentials:
    password: sealed://credentials.password
    username: gajanan@rafay.co
  endpoint: https://github.com/gajanan-rafay/test-repo
  options: {}
  secret:
    name: file://artifacts/gajanan-t/sealed-secret.yaml
  type: Git
