apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: avinash-gitops
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBHiFgpbcwrCpIznyMQGnL063vXkLnTbfBaX5RYMwumPNPqWaexWrIsqFd0UuCbkbl41TycaBlINAr90K/10ZhGN7aXeoC09api5B/Y+gyA+KMEv4FTuHTNVoSfU7hfHP33Uuy0CaZ3hGTYgjk25troMrEXqwR6uLj48Ld1dVTSk6y3KkrKz2dP2UEDLJC/F7LY8+rfRNkU4d9px57Qt1j7WJjTB1lyxTpNUYl8wPCD92i9IJvIXd7WQfXwo6e2JA3/Ry1siK6Kgp6BMDiZI+Iz87o38XquaIezCgXupzK/DsJPCIcbZ2XyI4bjZd11TrrIjf0gGhUxPWVwDs1AdPfsi/nAvG6FxzQ/kd6tJ81JuJBlK/WbI6V2B6wjjnRktqF3LfcV1KG9RbvcAC9oNf+OIHxJcYWUaZs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: avinash-gitops
      namespace: default

