apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: gajanan-test
  project: aniruddha-prj
spec:
  agents:
  - name: gaj-test
  credentials:
    password: sealed://credentials.password
    username: gajanan@rafay.co
  endpoint: https://github.com/gajanan-rafay/test-repo
  options: {}
  secret:
    name: file://artifacts/gajanan-test/sealed-secret.yaml
  type: Git
