apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: helm3-helmrepo-demo
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      repository: gajanan-test
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  drift:
    enabled: false
  namespace: new-ns-gajanan
  placement:
    selector: rafay.dev/clusterName=hardik-123
