apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: helm3-workload-upload
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/helm3-workload-upload/nginx-9.5.4.tgz
      valuesPaths:
      - name: file://artifacts/helm3-workload-upload/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  drift:
    enabled: false
  namespace: new-ns-gajanan
  placement:
    selector: rafay.dev/clusterName=hardik-123
  version: helm3-workload-upload-v1
