apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: helm3-helmrepo-234
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      chartName: nginx
      chartVersion: 9.5.4
      repository: default-bitnami
      valuesPaths:
      - name: file://artifacts/helm3-helmrepo-234/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  drift:
    enabled: false
  namespace: new-ns-gajanan
  placement:
    selector: rafay.dev/clusterName=hardik-123
  version: helm3-helmrepo-234-v2
