apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: helm3-upload-wk
  project: gajanan-prod-test
spec:
  artifact:
    artifact: {}
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  drift:
    enabled: false
  namespace: test-import-app
  placement: {}
