apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: new-ns-create
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/new-ns-create/new-ns-create.yaml
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: new-ns-create
  placement:
    selector: rafay.dev/clusterName=new-gajanan-prod-eks
  version: new-ns-create-v2
