apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: new-workload-helminhelm-v3
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      chartName: nginx
      repository: default-bitnami
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  drift:
    action: Deny
    enabled: true
  namespace: gaja-ns
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: gajanan-prod-test-mks-1
    - key: rafay.dev/clusterName
      value: gajanan-prod-test-eks-1
  version: v1
