apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: new-workload-yamlingit-v3-112
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      paths:
      - name: working-yamls/nginx-workload.yaml
      repository: gajanan-test
      revision: main
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: gaja-ns-1
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: prod-gajanan-mks-2ndapril
  version: v1
