apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: ssh-key-workload-v3-1
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/ssh-key-workload-v3-1/ssh.yaml
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: gaja-ns-1
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: gajanan-prod-test-mks-1
    - key: rafay.dev/clusterName
      value: gajanan-prod-test-eks-1
  version: v1
