apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: vault-wk
  project: gajanan-prod-test
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: vault-ns
  placement: {}
