apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: vault-helm-chart
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/vault-helm-chart/vault-helm-0.5.0.tar.gz
      valuesPaths:
      - name: file://artifacts/vault-helm-chart/vault-helm-050-values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  drift:
    enabled: false
  namespace: vault-ns
  placement:
    selector: rafay.dev/clusterName=prod-gajanan-mks-2ndapril
  version: vault-helm-chart-v1
