apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: new-wk-wizaed
  project: defaultproject
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: tb98ns01
  placement: {}
