apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bp-v3
  project: madhuproject
spec:
  base:
    name: default
    version: 1.13.0
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    enableVM: false
    monitoring:
      helmExporter:
        discovery: {}
        enabled: true
      kubeStateMetrics:
        discovery: {}
        enabled: true
      metricsServer:
        enabled: true
      nodeExporter:
        discovery: {}
        enabled: true
      prometheusAdapter:
        enabled: true
      resources: {}
  drift:
    enabled: false
  opaPolicy: {}
  placement:
    autoPublish: true
    fleetValues:
    - v3-fleet-03-t3
    - v3-fleet-04-t1
  sharing:
    enabled: false
  version: v2
