apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: madhubp1
  project: madhuproject
spec:
  base:
    name: default
    version: 1.13.0
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  opaPolicy: {}
  placement:
    fleetValues:
    - f1
  sharing:
    enabled: false
  version: v12
