apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tb103repo01
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCABW3grAXKdUkiz5yetx/xHG6p87X/OgeRi+gRPKbWnvwKQqQHkB86R5cIhQtsk8YF/PqLjBTT6LoG0EuNJaCWYfsiOqlYZtItpFGl+U5GKNf10ZyLg8r3x3UHWlS+OHSh0zr1Hu1pd65j5353qGuGz3oqUg4uMcKzxtQhhEQ1s0S/CqzUPonit8/wtfrDNH1XIOhRens8gW00UDv7ZcynZ4w56gbxTQp0HKBCTw0Zn4pifVOjKX3/CJvgZkrAHyyt3WUtfkB948JoJ+gAEVTYEQfA2DEO0qkOIms1E3FuZPDY4yT0nQEEUvqZOQGKdb4hmI1zti+NxX1P8xQXn/PyG9buPGmbSErXr5NqoSgOKbVvrZo+PCzlUxPoGKWcsM05BsdLBUMutc3KwbqFDKWIW4Mkhn5ehq8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: tb103repo01
      namespace: default

