apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: avinash
  project: aniruddha-prj
spec:
  base:
    name: default
    version: snapshot - 2022-01-18T06:53:31Z
  customAddons:
  - name: new-rctl-addon-helm3chart
    version: v1
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  sharing:
    enabled: false
  version: v1
