apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bp-v3
  project: aniruddha-prj
spec:
  base:
    name: default
    version: snapshot - 2022-01-10T10:44:03Z
  customAddons:
  - name: new-rctl-addon-gitrepohelm
    version: v1
  - name: new-rctl-addon-yamlingit
    version: v1
  - name: new-rctl-addon-helm3chart
    version: v1
  - name: new-rctl-addon-helmrepo
    version: v1
  - name: new-rctl-addon-helm3multivalue
    version: v1
  - name: new-rctl-addon-nativeyaml
    version: v1
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    enableVM: false
  drift:
    action: Deny
    enabled: true
  sharing:
    enabled: false
  version: v4
