apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: new-rctl-blueprint-postfix
  project: aniruddha-prj
spec:
  base:
    name: default
    version: snapshot - 2022-01-19T01:23:31Z
  customAddons:
  - name: new-rctl-addon-gitrepohelm
    version: v1
  defaultAddons:
    enableIngress: false
    enableLogging: false
    enableMonitoring: false
    enableVM: false
  drift:
    enabled: false
  sharing:
    enabled: false
  version: v1
