apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: v3-bp-1
  project: aniruddha-prj
spec:
  base:
    name: default
    version: snapshot - 2022-01-10T10:44:03Z
  customAddons:
  - name: new-addon-helminhelmrepo
    version: v1
  - name: new-addon-helmingitrepo
    version: v1
  - name: new-addon-yamlingitrepo
    version: v0
  - name: new-addon-nativeyaml
    version: v0
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    enableVM: false
  drift:
    action: Deny
    enabled: true
  sharing:
    enabled: false
  version: v5
