apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: webapp
  project: madhuproject
spec:
  drift:
    enabled: false
  limitRange:
    container: {}
    pod: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: madhueks-bp-ed
  resourceQuotas: {}
