apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: sad
  project: defaultproject
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: default-tb103-org01
  placement: {}
