apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: test
  project: defaultproject
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
  templateName: proc-mount
