apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: new-rctl-addon-helmrepo-postfix
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      chartName: nginx
      chartVersion: 9.5.4
      repository: default-bitnami
      valuesPaths:
      - name: file://artifacts/new-rctl-addon-helmrepo-postfix/nginx-values-1-with-rauto-automation-ecr-registry.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: new-rctl-addon-ns-postfix
  sharing:
    enabled: false
  version: v16
