apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: new-addon-helmchartwithvalues-v3-112
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/new-addon-helmchartwithvalues-v3-112/nginx-8.2.0-rafay.tgz
      valuesPaths:
      - name: file://artifacts/new-addon-helmchartwithvalues-v3-112/nginx-values-1-with-rauto-automation-ecr-registry.yaml
      - name: file://artifacts/new-addon-helmchartwithvalues-v3-112/nginx-values-3-with-rauto-automation-ecr-registry.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: gaj-ns
  sharing:
    enabled: false
  version: v1
