apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  description: description for version v1
  name: new-rctl-addon-gitrepohelm-v2
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      chartPath:
        name: working-helm/helm-multi-values/nginx-8.2.0-rafay.tgz
      repository: gajanan-test
      revision: main
      valuesPaths:
      - name: working-helm/helm-multi-values/nginx-values-1-with-rauto-automation-ecr-registry.yaml
      - name: working-helm/helm-multi-values/nginx-values-2-with-rauto-automation-ecr-registry.yaml
      - name: working-helm/helm-multi-values/nginx-values-3-with-rauto-automation-ecr-registry.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: new-rctl-addon-ns
  sharing:
    enabled: false
  version: v1
