apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  description: description for addon version v1
  name: new-rctl-addon-helm3chart-postfix
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/new-rctl-addon-helm3chart-postfix/nginx-9.5.4.tgz
      valuesPaths:
      - name: file://artifacts/new-rctl-addon-helm3chart-postfix/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: new-rctl-addon-ns-postfix
  sharing:
    enabled: false
  version: v1
