apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  description: description for addon version helmchartv1
  name: new-rctl-addon-helm3multivalue-v2
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/new-rctl-addon-helm3multivalue-v2/nginx-8.2.0-rafay.tgz
      valuesPaths:
      - name: file://artifacts/new-rctl-addon-helm3multivalue-v2/nginx-values-1-with-rauto-automation-ecr-registry.yaml
      - name: file://artifacts/new-rctl-addon-helm3multivalue-v2/nginx-values-3-with-rauto-automation-ecr-registry.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: new-rctl-addon-ns
  sharing:
    enabled: false
  version: v1
