apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  description: description for addon version addonv1
  name: new-rctl-addon-nativeyaml-v2
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/new-rctl-addon-nativeyaml-v2/nginx.yaml
    options: {}
    type: Yaml
  namespace: new-rctl-addon-ns
  sharing:
    enabled: false
  version: v1
