apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: test-addon
  project: gajanan-prod-test
spec:
  artifact:
    artifact:
      chartName: nginx
      chartVersion: 9.5.4
      repository: default-bitnami
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: gajanan-1
  sharing:
    enabled: false
  version: v4
