apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: avinash-gitops
  project: defaultproject
spec:
  agents:
  - name: avi-ss-test-1
  credentials:
    password: sealed://credentials.password
    username: avinash@rafay.co
  endpoint: https://github.com/avinash-rafay/gitops.git
  options: {}
  secret:
    name: file://artifacts/avinash-gitops/sealed-secret.yaml
  type: Git
