apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  annotations:
    rafay.dev/description: tb98repo01
  description: tb98repo01
  name: tb98repo01
  project: defaultproject
spec:
  agents:
  - name: tb98agent02
  credentials:
    password: sealed://credentials.password
    username: ambar@rafay.co
  endpoint: https://github.com/ambar-rafay/gitopstest.git
  options: {}
  secret:
    name: file://artifacts/tb98repo01/sealed-secret.yaml
  type: Git
