apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: test
  project: defaultproject
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
