apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: test-pipe
  project: defaultproject
spec:
  active: true
  sharing:
    enabled: false
  stages:
  - config:
      destinationRepo: {}
      gitToSystemSync: true
      includedResources:
      - name: '*'
      sourceAsDestination: true
      sourceRepo:
        path:
          name: new-sync
        repository: gajanan-test
        revision: main
      systemToGitSync: true
    name: stage-1
    type: SystemSync
  triggers:
  - config:
      cronExpression: '* * * * *'
      repo:
        paths:
        - name: new-sync
        repository: gajanan-test
        revision: main
    name: new-cronjob
    type: Cron
