apiVersion: apps.k8smgmt.io/v3
kind: Override
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: valuesFile
  name: test-addco
  project: defaultproject
spec:
  placement: {}
  resource:
    selector:
      name: test-addon
    type: Addon
  type: Yaml
  valuesPath:
    name: file://artifacts/test-addco/test-addco.yaml
