apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test-helmrepo
  project: defaultproject
spec:
  artifact:
    artifact:
      chartName: nginx
      chartVersion: 9.5.4
      repository: default-bitnami
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  drift:
    enabled: false
  namespace: gajanan-ns
  placement:
    selector: rafay.dev/clusterName=gajanan-tb-mks-co
  version: test-helmrepo-v1
