apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test-helm3
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/test-helm3/nginx-9.5.4.tgz
      valuesPaths:
      - name: file://artifacts/test-helm3/values.yaml
      - name: file://artifacts/test-helm3/nginx-values-3-with-rauto-automation-ecr-registry.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  drift:
    enabled: false
  namespace: default-rafay
  placement:
    selector: rafay.dev/clusterName=gajanan-tb-mks-co
  version: test-helm3-v1
