apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test-wk
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/test-wk/test-wk.yaml
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: gajanan-ns
  placement:
    selector: rafay.dev/clusterName=gajanan-tb-mks-co
