apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: new-rctl-addon-nativeyaml
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/new-rctl-addon-nativeyaml/nginx.yaml
    options: {}
    type: Yaml
  namespace: new-rctl-addon-ns
  sharing:
    enabled: false
