apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: gajanan-ns-v3
  project: gajanan-prod-test
spec:
  drift:
    enabled: false
  limitRange:
    container: {}
    pod: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: gajanan-prod-test-mks-1
    - key: rafay.dev/clusterName
      value: gajanan-prod-test-eks-1
  resourceQuotas: {}
