apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: new-ns-gajanan
  project: gajanan-prod-test
spec:
  drift:
    enabled: false
  limitRange:
    container: {}
    pod: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: hardik-123
  resourceQuotas: {}
