apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: vault-ns
  project: gajanan-prod-test
spec:
  drift:
    enabled: false
  limitRange:
    container: {}
    pod: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: prod-gajanan-mks-2ndapril
  resourceQuotas: {}
